import { test, expect, type Page } from '@playwright/test'
import { initialData } from '../../src/lib/model'
const nav = (page: Page, name: string) => page.getByRole('navigation').getByRole('button', { name: new RegExp('^' + name) }).click()
test('existing account links, cash costs, split payouts, funding, resets, edits and new logger names persist', async ({ page }) => {
  const data = initialData()
  data.trades = [{ id: 'trade', createdAt: '2026-08-01', updatedAt: '2026-08-01', values: { date: '2026-08-01', timeIn: '09:30', timeOut: '10:00', direction: 'LONG', contract: 'MNQ', size: 3, pnl: 500, pnlUnit: 'POINTS', account: 'PROP1', strategy: 'ORB' } }]
  await page.goto('/'); await nav(page, 'Settings')
  await page.getByLabel('Import backup file', { exact: true }).setInputFiles({ name: 'trade.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) })
  await page.getByRole('button', { name: 'Back up current data & restore' }).click()
  await nav(page, 'Account manager'); await page.getByLabel('Managed account').selectOption('PROP1')
  await page.getByRole('button', { name: 'Set up account details' }).click()
  await page.getByLabel('Prop firm', { exact: true }).fill('Test Prop')
  await page.getByLabel('Account purchase cost', { exact: true }).fill('150')
  await page.getByLabel('Maximum drawdown amount', { exact: true }).fill('2000')
  await page.getByLabel('Daily loss limit (DLL)', { exact: true }).fill('500')
  await page.getByLabel('Drawdown type', { exact: true }).selectOption('live')
  await page.getByRole('button', { name: 'Save account', exact: true }).click()
  const detail = (name: string) => page.locator('.account-detail-grid>div').filter({ has: page.getByText(name, { exact: true }) })
  await expect(detail('Trading balance')).toContainText('$51,000.00')
  const openAction = async (type: string, at: string) => { await page.getByRole('button', { name: 'Record action', exact: true }).click(); await page.getByLabel('Action', { exact: true }).selectOption(type); await page.getByLabel('Action date/time', { exact: true }).fill(at) }
  await openAction('payout', '2026-08-01T12:00')
  await page.getByLabel('Trading balance deduction', { exact: true }).fill('1000')
  await page.getByLabel('Your payout share (%)', { exact: true }).fill('80')
  await expect(page.getByLabel('Actual cash received', { exact: true })).toHaveValue('800')
  await page.getByRole('button', { name: 'Save action', exact: true }).click()
  await expect(detail('Trading balance')).toContainText('$50,000.00'); await expect(detail('Net real cash')).toContainText('$650.00')
  await openAction('reset', '2026-08-02T08:00')
  await page.getByLabel('Cash cost / fee', { exact: true }).fill('80')
  await page.getByRole('button', { name: 'Save action', exact: true }).click()
  await openAction('funded', '2026-08-02T09:00')
  await page.getByLabel('Cash cost / fee', { exact: true }).fill('125')
  await page.getByLabel('New trading balance (optional)', { exact: true }).fill('50000')
  await page.getByRole('button', { name: 'Save action', exact: true }).click()
  await expect(detail('Total costs')).toContainText('$355.00')
  await expect(detail('Net real cash')).toContainText('$445.00')
  await page.getByRole('button', { name: 'Edit Payout 2026-08-01T12:00:00', exact: true }).click()
  await page.getByLabel('Your payout share (%)', { exact: true }).fill('90')
  await page.getByRole('button', { name: 'Save action', exact: true }).click()
  await expect(detail('Actual payouts received')).toContainText('$900.00')
  await page.getByRole('heading', { name: 'Account manager.' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/account-manager.png' })
  await page.reload(); await nav(page, 'Account manager'); await page.getByLabel('Managed account').selectOption('PROP1')
  await expect(detail('Total costs')).toContainText('$355.00')
  await expect(detail('Actual payouts received')).toContainText('$900.00')
  await page.getByRole('button', { name: 'Delete Account reset 2026-08-02T08:00:00', exact: true }).click()
  await page.getByRole('button', { name: 'Delete action', exact: true }).click()
  await expect(detail('Total costs')).toContainText('$275.00')
  await page.getByRole('button', { name: 'Add account', exact: true }).click()
  await page.getByLabel('Account name', { exact: true }).fill('new eval')
  await page.getByRole('button', { name: 'Save account', exact: true }).click()
  await nav(page, 'Trade log'); await expect(page.locator('#field-account-options option[value="NEW EVAL"]')).toHaveCount(1)
  await nav(page, 'Master trade log'); await expect(page.locator('tbody tr')).toHaveCount(1)
})
