import { test, expect, type Page } from '@playwright/test'
const nav = (page: Page, name: string) => page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: new RegExp(`^${name}( \\d+)?$`) }).click()
const saved = (page: Page) => expect(page.locator('.save-status')).toHaveText('Saved locally')
async function essentials(page: Page) {
  await page.locator('#field-date').fill('2026-09-01')
  await page.locator('#field-timeIn').fill('09:30')
  await page.locator('#field-timeOut').fill('10:00')
  await page.locator('#field-direction').selectOption('LONG')
  await page.locator('#field-contract').fill('ES')
  await page.locator('#field-size').fill('1')
  await page.locator('#field-pnl').fill('0')
  await page.locator('#field-account').fill('Sim')
  await page.locator('#field-strategy').fill('Breakout')
}
test.beforeEach(async ({ page }) => { await page.goto('/'); await expect(page.getByRole('heading', { name: 'Performance overview.' })).toBeVisible() })
test('unfinished → completed → edited → deleted, including zero PnL', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await nav(page, 'Trade log')
  await page.locator('#field-contract').fill('ES')
  await page.locator('#field-pnl').fill('0')
  await page.getByRole('button', { name: 'Save unfinished trade' }).click()
  await expect(page.locator('.draft-card')).toHaveCount(1)
  await nav(page, 'Master trade log'); await expect(page.getByRole('heading', { name: 'A clean slate.' })).toBeVisible()
  await nav(page, 'Trade log'); await page.getByRole('button', { name: 'Finish entry' }).click()
  await expect(page.locator('#field-pnl')).toHaveValue('0')
  await essentials(page)
  await page.locator('#field-notes').fill('A disciplined breakeven.')
  await page.getByRole('button', { name: 'Save completed trade' }).click()
  await expect(page.locator('.draft-card')).toHaveCount(0)
  await nav(page, 'Master trade log'); await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Edit trade ES 2026-09-01' }).click()
  await expect(page.locator('#field-notes')).toHaveValue('A disciplined breakeven.')
  await page.locator('#field-pnl').fill('125.50')
  await page.getByRole('button', { name: 'Save completed trade' }).click(); await saved(page)
  await page.reload(); await nav(page, 'Master trade log'); await expect(page.locator('tbody')).toContainText('$125.50')
  await page.getByRole('button', { name: 'Delete trade ES 2026-09-01' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete trade', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A clean slate.' })).toBeVisible()
  expect(errors).toEqual([])
})
test('custom fields become required, learn options and generate analytics', async ({ page }) => {
  await nav(page, 'Settings'); await page.getByRole('button', { name: 'Add characteristic', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Name', { exact: true }).fill('Mood')
  await dialog.getByLabel('Dropdown options').fill('Happy, Sad, Tired')
  await dialog.getByLabel('Required to complete a trade').check()
  await dialog.getByRole('button', { name: 'Save characteristic' }).click()
  await nav(page, 'Trade log'); await essentials(page)
  await expect(page.getByRole('button', { name: 'Save unfinished trade' })).toBeVisible()
  await page.getByLabel('Mood').fill('Focused')
  await page.getByRole('button', { name: 'Save completed trade' }).click(); await saved(page)
  await nav(page, 'Dashboard'); await page.locator('summary').filter({ hasText: 'Mood' }).click()
  await expect(page.locator('details[open]')).toContainText('FOCUSED')
  await nav(page, 'Settings'); await page.getByRole('button', { name: 'Edit Mood', exact: true }).click()
  await expect(dialog.getByLabel('Dropdown options')).toHaveValue('HAPPY, SAD, TIRED, FOCUSED')
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Add characteristic', exact: true }).click()
  await dialog.getByLabel('Name', { exact: true }).fill('Energy')
  await dialog.getByLabel('Value type').selectOption('score')
  await dialog.getByLabel('Maximum', { exact: true }).fill('10')
  await dialog.getByLabel('Required to complete a trade').check()
  await expect(dialog).toContainText('from 1 to 0')
  await dialog.getByRole('button', { name: 'Save characteristic' }).click()
  await nav(page, 'Trade log'); await expect(page.locator('.draft-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Finish entry' }).click()
  await page.getByLabel('Energy').selectOption('10')
  await page.getByRole('button', { name: 'Save completed trade' }).click()
  await nav(page, 'Master trade log'); await expect(page.locator('tbody tr')).toHaveCount(1)
})
test('invalid optional values cannot be saved and unfinished entries can be deleted', async ({ page }) => {
  await nav(page, 'Trade log'); await essentials(page)
  await page.locator('#field-mhpResilience').fill('150.01')
  await page.getByRole('button', { name: 'Save unfinished trade' }).click()
  await expect(page.getByText('Maximum is 150', { exact: true })).toBeVisible()
  await page.locator('#field-mhpResilience').fill('-150')
  await page.locator('#field-timeOut').fill('')
  await page.getByRole('button', { name: 'Save unfinished trade' }).click()
  await expect(page.locator('.draft-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Delete unfinished trade ES 2026-09-01' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete trade', exact: true }).click()
  await expect(page.locator('.draft-card')).toHaveCount(0)
})
test('long daily journal pages stay attached to their dates and themes persist', async ({ page }) => {
  await nav(page, 'Daily journal'); await page.getByLabel('Journal date', { exact: true }).fill('2026-09-01')
  const longText = 'Patient entries, thoughtful exits.\n'.repeat(1500)
  await page.getByLabel('Journal entry', { exact: true }).fill(longText)
  await page.getByRole('button', { name: 'Next day', exact: true }).click()
  await page.getByLabel('Journal entry', { exact: true }).fill('Second day, separate thoughts.')
  await page.getByRole('button', { name: 'Previous day', exact: true }).click()
  await expect(page.getByLabel('Journal entry', { exact: true })).toHaveValue(longText)
  await page.getByRole('button', { name: 'Switch to light mode' }).click(); await saved(page)
  await page.reload(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await nav(page, 'Daily journal'); await page.getByLabel('Journal date', { exact: true }).fill('2026-09-02')
  await expect(page.getByLabel('Journal entry', { exact: true })).toHaveValue('Second day, separate thoughts.')
})
test('sample analytics, combined filters, export, both themes and narrow layout', async ({ page }) => {
  await page.getByRole('button', { name: 'Explore sample data' }).click(); await saved(page)
  await expect(page.locator('.stat-card').first()).toContainText('64 completed trades')
  await expect(page.getByRole('heading', { name: 'Performance breakdown' })).toBeVisible()
  await page.screenshot({ path: 'test-results/dashboard-dark.png', fullPage: true })
  await page.getByRole('button', { name: 'Switch to light mode' }).click(); await saved(page)
  await page.screenshot({ path: 'test-results/dashboard-light.png', fullPage: true })
  await page.getByLabel('Add filter', { exact: true }).selectOption('contract')
  await page.getByLabel('Filter Contract', { exact: true }).selectOption('ES')
  await page.getByLabel('Add filter', { exact: true }).selectOption('strategy')
  await page.getByLabel('Filter Strategy', { exact: true }).selectOption('BREAKOUT')
  await expect(page.locator('.stat-card').first()).toContainText('0 completed trades')
  await page.getByRole('button', { name: 'Reset filters' }).click()
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export breakdown' }).click()
  expect((await download).suggestedFilename()).toBe('turbo-breakdown.csv')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true })
  await nav(page, 'Settings'); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Remove sample trades', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Remove samples', exact: true }).click()
  await nav(page, 'Master trade log'); await expect(page.getByRole('heading', { name: 'A clean slate.' })).toBeVisible()
})
test('backup restore validates files and restores exported records', async ({ page }) => {
  await page.getByRole('button', { name: 'Explore sample data' }).click(); await saved(page); await nav(page, 'Settings')
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export backup', exact: true }).click()
  const path = await (await download).path()
  await page.getByRole('button', { name: 'Remove sample trades', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Remove samples', exact: true }).click()
  await page.getByLabel('Import backup file', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"version":1}') })
  await expect(page.getByRole('alert')).toContainText('Unsupported or incomplete backup')
  await page.getByLabel('Import backup file', { exact: true }).setInputFiles(path!)
  await expect(page.getByRole('dialog')).toContainText('64 trades')
  await page.getByRole('button', { name: 'Back up current data & restore', exact: true }).click(); await saved(page)
  await nav(page, 'Dashboard'); await expect(page.locator('.stat-card').first()).toContainText('64 completed trades')
})
test('failed saves show an error and resubmitting never duplicates a trade', async ({ page }) => {
  await nav(page, 'Trade log'); await essentials(page)
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (...args) {
      IDBObjectStore.prototype.put = original
      throw new Error(`Simulated storage failure for ${args.length} argument(s)`)
    }
  })
  await page.getByRole('button', { name: 'Save completed trade' }).click()
  await expect(page.getByRole('alert')).toContainText('haven’t been saved')
  await expect(page.locator('#field-pnl')).toHaveValue('0')
  await page.getByRole('button', { name: 'Save completed trade' }).click(); await saved(page)
  await nav(page, 'Master trade log'); await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.reload(); await nav(page, 'Master trade log'); await expect(page.locator('tbody tr')).toHaveCount(1)
})
