import { test, expect, type Page } from '@playwright/test'
const nav = (page: Page, name: string) => page.getByRole('navigation').getByRole('button', { name: new RegExp('^' + name) }).click()
test('last-used dashboard and master filters persist independently across navigation, reload and reset', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Explore sample data' }).click()
  await page.getByLabel('From date', { exact: true }).fill('2026-09-01')
  await page.getByLabel('Add filter', { exact: true }).selectOption('contract')
  await page.getByLabel('Filter Contract', { exact: true }).selectOption('ES')
  await nav(page, 'Master trade log')
  await expect(page.getByLabel('From date', { exact: true })).toHaveValue('')
  await page.getByLabel('Add filter', { exact: true }).selectOption('pnl')
  await page.getByLabel('PnL minimum', { exact: true }).fill('-100')
  await page.getByLabel('PnL maximum', { exact: true }).fill('250')
  await page.getByLabel('Search trades', { exact: true }).fill('pullback')
  await expect(page.locator('.save-status')).toHaveText('Saved locally')
  await page.reload()
  await expect(page.getByLabel('From date', { exact: true })).toHaveValue('2026-09-01')
  await expect(page.getByLabel('Filter Contract', { exact: true })).toHaveValue('ES')
  await nav(page, 'Master trade log')
  await expect(page.getByLabel('PnL minimum', { exact: true })).toHaveValue('-100')
  await expect(page.getByLabel('PnL maximum', { exact: true })).toHaveValue('250')
  await expect(page.getByLabel('Search trades', { exact: true })).toHaveValue('pullback')
  await page.getByRole('button', { name: 'Reset filters', exact: true }).click()
  await page.getByLabel('Search trades', { exact: true }).fill('')
  await expect(page.locator('.save-status')).toHaveText('Saved locally')
  await page.reload(); await nav(page, 'Master trade log')
  await expect(page.getByLabel('PnL minimum', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Search trades', { exact: true })).toHaveValue('')
  await nav(page, 'Dashboard')
  await expect(page.getByLabel('Filter Contract', { exact: true })).toHaveValue('ES')
})
