import { test, expect, type Page } from '@playwright/test'

const nav = (page: Page, name: string) => page.getByRole('navigation').getByRole('button', { name, exact: true }).click()
const toggle = (page: Page, enabled: boolean) => page.getByRole('button', { name: enabled ? 'Enable minimalist mode' : 'Exit minimalist mode' }).click()

test('compact entry retains unsaved values across modes, resumes drafts and completes custom characteristics', async ({ page }) => {
  await page.goto('/')
  await nav(page, 'Settings')
  await page.getByRole('button', { name: 'Add characteristic', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Name', { exact: true }).fill('Mood')
  await dialog.getByLabel('Dropdown options').fill('Calm, Focused')
  await dialog.getByLabel('Required to complete a trade').check()
  await dialog.getByRole('button', { name: 'Save characteristic' }).click()
  await nav(page, 'Trade log')
  await page.locator('#field-contract').fill('mnq')
  await page.locator('#field-notes').fill('Keep My case\nand newlines.')
  await toggle(page, true)
  await page.setViewportSize({ width: 1440, height: 140 })
  await expect(page.locator('#field-contract')).toHaveValue('MNQ')
  await expect(page.locator('#field-notes')).toHaveValue('Keep My case\nand newlines.')
  await page.getByLabel('Mood', { exact: false }).fill('focused')
  await toggle(page, false)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.getByLabel('Mood', { exact: false })).toHaveValue('FOCUSED')
  await expect(page.locator('#field-notes')).toHaveValue('Keep My case\nand newlines.')
  await toggle(page, true)
  await page.setViewportSize({ width: 1440, height: 140 })
  await page.getByRole('button', { name: 'Save unfinished', exact: true }).click()
  await expect(page.getByLabel('Resume unfinished trade')).toContainText('1 unfinished')
  await expect(page.locator('.quick-status')).toHaveText('Saved locally')
  await page.reload()
  await expect(page.getByRole('form', { name: 'Minimalist trade entry' })).toBeVisible()
  await page.getByLabel('Resume unfinished trade').selectOption({ index: 1 })
  await expect(page.getByLabel('Mood', { exact: false })).toHaveValue('FOCUSED')
  for (const [id, value] of Object.entries({ date: '2026-09-01', timeIn: '09:30', timeOut: '10:00', size: '1', pnl: '0', account: 'sim', strategy: 'orb' })) await page.locator(`#field-${id}`).fill(value)
  await expect(page.locator('#field-direction')).toHaveText('LONG')
  await page.getByRole('button', { name: 'Save trade', exact: true }).click()
  await expect(page.getByLabel('Resume unfinished trade')).toContainText('0 unfinished')
  await toggle(page, false)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await nav(page, 'Master trade log')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Edit trade MNQ 2026-09-01' }).click()
  await expect(page.locator('#field-direction')).toHaveText('LONG')
  await page.locator('#field-direction').click()
  await toggle(page, true)
  await expect(page.locator('#field-direction')).toHaveText('SHORT')
  await page.getByRole('button', { name: 'Save trade', exact: true }).click()
  await expect(page.locator('#field-direction')).toHaveText('LONG')
  await toggle(page, false)
  await nav(page, 'Master trade log')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.locator('tbody tr')).toContainText('SHORT')
  await page.getByRole('button', { name: 'Edit trade MNQ 2026-09-01' }).click()
  await toggle(page, true)
  await page.setViewportSize({ width: 640, height: 140 })
  await expect(page.locator('#field-pnl')).toHaveValue('0')
  await page.getByRole('button', { name: 'Delete current trade' }).click()
  await expect(dialog.getByRole('button', { name: 'Delete trade', exact: true })).toBeInViewport()
  await dialog.getByRole('button', { name: 'Delete trade', exact: true }).click()
  await expect(page.getByLabel('Resume unfinished trade')).toContainText('New trade')
  await toggle(page, false)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await nav(page, 'Master trade log')
  await expect(page.getByRole('heading', { name: 'A clean slate.' })).toBeVisible()
})

test('short strip scrolls by wheel and keyboard, validates offscreen fields and fits both themes', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await toggle(page, true)
  await page.setViewportSize({ width: 1440, height: 140 })
  const row = page.getByRole('region', { name: 'Trade characteristics' })
  await expect(page.locator('#field-direction')).toHaveText('LONG')
  await page.locator('#field-direction').click()
  await expect(page.locator('#field-direction')).toHaveText('SHORT')
  await page.locator('#field-direction').press('Space')
  await expect(page.locator('#field-direction')).toHaveText('LONG')
  await expect(row.locator('.form-field')).toHaveCount(22)
  await row.hover()
  await page.mouse.wheel(0, 700)
  await expect.poll(() => row.evaluate(el => el.scrollLeft)).toBeGreaterThan(0)
  await page.locator('#field-size').fill('3')
  await page.locator('#field-size').hover()
  await page.mouse.wheel(0, 300)
  await expect(page.locator('#field-size')).toHaveValue('3')
  await page.locator('#field-hgResilience').focus()
  await page.keyboard.press('Tab')
  await expect(page.locator('#field-setupGrade')).toBeFocused()
  await expect(page.locator('#field-setupGrade')).toBeInViewport()
  await page.locator('#field-mhpResilience').fill('151')
  await page.locator('#field-date').focus()
  await page.getByRole('button', { name: 'Save unfinished', exact: true }).click()
  await expect(page.locator('#field-mhpResilience')).toBeFocused()
  await expect(page.getByText('Maximum is 150', { exact: true })).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Save unfinished', exact: true })).toBeInViewport()
  await page.locator('#field-mhpResilience').fill('12.5')
  await page.locator('#field-date').focus()
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight && document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/minimalist-dark.png' })
  await page.getByRole('button', { name: 'Switch to light mode' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.screenshot({ path: 'test-results/minimalist-light.png' })
  await page.setViewportSize({ width: 640, height: 140 })
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight && document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect(page.getByRole('button', { name: 'Exit minimalist mode' })).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Save unfinished', exact: true })).toBeInViewport()
  await page.screenshot({ path: 'test-results/minimalist-small.png' })
  expect(errors).toEqual([])
})
