import { test, expect, type Page } from '@playwright/test'
import { initialData } from '../../src/lib/model'
const nav = (page: Page, name: string) => page.getByRole('navigation').getByRole('button', { name: new RegExp('^' + name) }).click()
test('legacy RR backfill, point entry, both dashboard units, automated toggles and multiplier updates persist', async ({ page }) => {
  const old = initialData()
  old.fields = old.fields.filter(f => !['pnlUnit', 'tradeRR', 'realizedRR'].includes(f.id))
  old.trades = [{ id: 'old', createdAt: '2026-09-01', updatedAt: '2026-09-01', values: { date: '2026-09-01', timeIn: '09:30', timeOut: '10:00', direction: 'LONG', contract: 'MNQ', size: 3, pnl: 120, account: 'SIM', strategy: 'ORB', stopLoss: 10, takeProfit: 30, notes: 'Original notes' } }]
  await page.goto('/'); await nav(page, 'Settings')
  await page.getByLabel('Import backup file', { exact: true }).setInputFiles({ name: 'old.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(old)) })
  await page.getByRole('button', { name: 'Back up current data & restore' }).click()
  await nav(page, 'Master trade log')
  await expect(page.locator('tbody')).toContainText('3 R'); await expect(page.locator('tbody')).toContainText('2 R')
  await page.getByRole('button', { name: 'Edit trade MNQ 2026-09-01' }).click()
  await page.locator('#field-pnlUnit').selectOption('POINTS'); await page.locator('#field-pnl').fill('25')
  await expect(page.locator('#field-tradeRR')).toHaveText('3 R')
  await expect(page.locator('#field-realizedRR')).toHaveText('0.83 R')
  await page.getByRole('button', { name: 'Save completed trade' }).click()
  await nav(page, 'Dashboard'); await page.getByLabel('Dashboard PnL display').selectOption('both')
  await expect(page.getByRole('region', { name: 'Dollars analytics', exact: true }).locator('.stat-card').first()).toContainText('$50.00')
  await expect(page.getByRole('region', { name: 'Points analytics', exact: true }).locator('.stat-card').first()).toContainText('25 pts')
  await page.screenshot({ path: 'test-results/pnl-both.png', fullPage: false })
  await nav(page, 'Settings')
  await page.getByRole('region', { name: 'Automated characteristics' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/automated-settings.png' })
  await expect(page.locator('.settings-table')).not.toContainText('Realized RR')
  const automated = page.getByRole('region', { name: 'Automated characteristics' })
  await automated.getByLabel('Trade RR enabled', { exact: true }).uncheck()
  await automated.getByLabel('Realized RR enabled', { exact: true }).uncheck()
  await nav(page, 'Trade log'); await expect(page.locator('#field-tradeRR')).toHaveCount(0)
  await nav(page, 'Master trade log'); await expect(page.getByRole('button', { name: 'Trade RR', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Columns', exact: true }).click()
  await page.getByRole('dialog').getByRole('checkbox', { name: 'Trade RR Removed', exact: true }).check()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.locator('tbody')).toContainText('3 R')
  await nav(page, 'Settings'); await automated.getByLabel('Realized RR enabled', { exact: true }).check()
  await page.getByText('Contract multipliers (USD per full point per contract)', { exact: true }).click()
  await page.getByRole('button', { name: 'Edit MNQ', exact: true }).click()
  await page.getByLabel('Value per point', { exact: true }).fill('4')
  await page.getByRole('button', { name: 'Save multiplier', exact: true }).click()
  await page.reload(); await expect(page.getByLabel('Dashboard PnL display')).toHaveValue('both')
  await expect(page.getByRole('region', { name: 'Dollars analytics', exact: true }).locator('.stat-card').first()).toContainText('$100.00')
  await nav(page, 'Master trade log'); await expect(page.locator('tbody')).toContainText('25 pts'); await expect(page.locator('tbody')).toContainText('0.83 R')
})
