import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { initialData } from '../../src/lib/model'

const nav = (page: Page, name: string) => page.getByRole('navigation').getByRole('button', { name, exact: true }).click()
async function showHistory(page: Page) {
  await page.getByRole('button', { name: 'Columns', exact: true }).click()
  const dialog = page.getByRole('dialog')
  for (const name of ['DD ratio (%)', 'Mood', 'Notes', 'Setup grade', 'lostDefinition']) {
    const checkbox = dialog.getByRole('checkbox', { name: name + ' Removed', exact: true })
    await expect(checkbox).not.toBeChecked()
    await checkbox.check()
  }
  await dialog.getByRole('button', { name: 'Done', exact: true }).click()
}
test('remove default and custom fields, edit history, export, reload and restore without losing values', async ({ page }) => {
  const data = initialData()
  const note = 'Keep My Notes.\n' + 'A detailed reflection.\n'.repeat(200)
  data.fields.push({ id: 'mood', name: 'Mood', type: 'text', required: false, filter: true, analyze: true, options: ['CALM'] })
  data.trades.push({ id: 'history', createdAt: '2026-09-01', updatedAt: '2026-09-01', values: { date: '2026-09-01', timeIn: '09:30', timeOut: '10:00', direction: 'LONG', contract: 'ES', size: 1, pnl: 0, account: 'SIM', strategy: 'ORB', ddRatio: 12.75, setupGrade: 'A+', mood: 'CALM', notes: note, lostDefinition: 'Original value' } })
  await page.goto('/')
  await nav(page, 'Settings')
  await page.getByLabel('Import backup file', { exact: true }).setInputFiles({ name: 'history.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) })
  await page.getByRole('button', { name: 'Back up current data & restore' }).click()
  await expect(page.locator('.save-status')).toHaveText('Saved locally')
  for (const name of ['DD ratio (%)', 'Mood', 'Notes', 'Setup grade']) await page.getByRole('button', { name: `Remove ${name}`, exact: true }).click()
  await expect(page.locator('.settings-table')).not.toContainText('DD ratio (%)')
  await page.reload()
  await nav(page, 'Trade log')
  for (const id of ['ddRatio', 'mood', 'notes']) await expect(page.locator(`#field-${id}`)).toHaveCount(0)
  await page.getByRole('button', { name: 'Enable minimalist mode' }).click()
  for (const id of ['ddRatio', 'mood', 'notes']) await expect(page.locator(`#field-${id}`)).toHaveCount(0)
  await page.getByRole('button', { name: 'Exit minimalist mode' }).click()
  await nav(page, 'Master trade log')
  await expect(page.locator('.master-table thead')).not.toContainText('Setup grade')
  await expect(page.locator('.master-table thead')).not.toContainText('DD ratio (%)')
  await expect(page.getByLabel('Add filter', { exact: true }).locator('option[value="setupGrade"]')).toHaveCount(0)
  await showHistory(page)
  await expect(page.locator('tbody')).toContainText('A+')
  await expect(page.locator('tbody')).toContainText('12.75%')
  await expect(page.locator('tbody')).toContainText('CALM')
  await expect(page.locator('tbody')).toContainText('Original value')
  const notes = page.getByRole('button', { name: 'Read trade notes' })
  await expect(page.locator('.master-table')).not.toContainText('Keep My Notes.')
  await notes.hover()
  await expect(page.getByRole('tooltip')).toContainText('Keep My Notes.')
  await expect(page.getByRole('tooltip')).toBeInViewport()
  expect(await page.locator('.trade-notes-preview>div').evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true)
  await page.screenshot({ path: 'test-results/trade-notes-preview.png' })
  await page.getByRole('heading', { name: 'Master trade log.' }).hover()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await notes.focus()
  await expect(page.getByRole('tooltip')).toContainText('Keep My Notes.')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await notes.click()
  await expect(page.getByRole('dialog')).toContainText('Keep My Notes.')
  await expect(page.locator('.trade-notes-full')).toHaveText(note)
  await page.getByRole('dialog').getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.getByRole('button', { name: 'Columns', exact: true }).click()
  await page.getByRole('button', { name: 'Use active characteristics', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Setup grade Removed', exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.locator('.master-table thead')).not.toContainText('Setup grade')
  await page.getByLabel('Search trades').fill('Original value')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Edit trade ES 2026-09-01' }).click()
  await expect(page.locator('#field-ddRatio')).toHaveCount(0)
  await page.locator('#field-pnl').fill('125')
  await page.getByRole('button', { name: 'Save completed trade' }).click()
  await nav(page, 'Master trade log')
  await expect(page.locator('tbody')).toContainText('$125.00')
  await expect(page.locator('.master-table thead')).not.toContainText('Setup grade')
  await expect(page.locator('.master-table thead')).not.toContainText('DD ratio (%)')
  await expect(page.getByLabel('Add filter', { exact: true }).locator('option[value="setupGrade"]')).toHaveCount(0)
  await showHistory(page)
  await expect(page.locator('tbody')).toContainText('A+')
  await expect(page.locator('tbody')).toContainText('12.75%')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click()
  const csv = await readFile((await (await download).path())!, 'utf8')
  for (const value of ['DD ratio (%)', '12.75', 'CALM', 'Keep My Notes.', 'Original value']) expect(csv).toContain(value)
  await nav(page, 'Settings')
  const backupDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export backup', exact: true }).click()
  const backupPath = (await (await backupDownload).path())!
  await page.getByLabel('Import backup file', { exact: true }).setInputFiles(backupPath)
  await page.getByRole('button', { name: 'Back up current data & restore' }).click()
  await page.locator('summary').filter({ hasText: 'Removed characteristics' }).click()
  for (const name of ['DD ratio (%)', 'Mood', 'Notes', 'Setup grade']) await page.getByRole('button', { name: `Restore ${name}`, exact: true }).click()
  await nav(page, 'Master trade log')
  await page.getByRole('button', { name: 'Edit trade ES 2026-09-01' }).click()
  await expect(page.locator('#field-setupGrade')).toHaveValue('A+')
  await expect(page.locator('#field-ddRatio')).toHaveValue('12.75')
  await expect(page.locator('#field-mood')).toHaveValue('CALM')
  await expect(page.locator('#field-notes')).toHaveValue(note)
})

test('removed date and direction are absent from fresh trades and required rules return on restore', async ({ page }) => {
  await page.goto('/')
  await nav(page, 'Settings')
  for (const name of ['Date', 'Long / short', 'Account']) await page.getByRole('button', { name: `Remove ${name}`, exact: true }).click()
  await nav(page, 'Trade log')
  for (const id of ['date', 'direction', 'account']) await expect(page.locator(`#field-${id}`)).toHaveCount(0)
  for (const [id, value] of Object.entries({ timeIn: '09:30', timeOut: '10:00', contract: 'ES', size: '1', pnl: '0', strategy: 'ORB' })) await page.locator(`#field-${id}`).fill(value)
  await page.getByRole('button', { name: 'Save completed trade' }).click()
  await nav(page, 'Master trade log')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await nav(page, 'Settings')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export backup', exact: true }).click()
  const saved = JSON.parse(await readFile((await (await download).path())!, 'utf8'))
  expect(saved.trades[0].values.date).toBeUndefined()
  expect(saved.trades[0].values.direction).toBeUndefined()
  await page.locator('summary').filter({ hasText: 'Removed characteristics' }).click()
  await page.getByRole('button', { name: 'Restore Account', exact: true }).click()
  await page.getByRole('navigation').getByRole('button', { name: /^Trade log/ }).click()
  await expect(page.locator('.draft-card')).toHaveCount(1)
})
