const { _electron: electron, expect } = require('@playwright/test')
const assert = require('node:assert/strict')
const { mkdtempSync, existsSync } = require('node:fs')
const { tmpdir } = require('node:os')
const path = require('node:path')
const { version } = require('../package.json')
const asar = require('@electron/asar')

async function main() {
  const directory = mkdtempSync(path.join(tmpdir(), 'turbo-release-test-'))
  const folder = path.resolve(__dirname, '../release', version, 'win-unpacked')
  const executablePath = path.join(folder, 'Turbo Trading Journal.exe')
  assert.ok(existsSync(executablePath), 'Build the Windows release first')
  const files = asar.listPackage(path.join(folder, 'resources/app.asar'))
  assert.ok(!files.some(name => /\.(db|sqlite|sqlite3)(-|$)|[\\/](?:tests|\.test-data|\.git|test-results)[\\/]/i.test(name)), 'Package must exclude personal databases, backups, source control and tests')
  const env = { ...process.env, TURBO_TEST_DATA_DIR: directory }
  delete env.ELECTRON_RUN_AS_NODE
  delete env.VITE_DEV_SERVER_URL
  let app
  try {
    app = await electron.launch({ executablePath, env, timeout: 30000 })
    let page = await app.firstWindow()
    await expect(page.getByRole('heading', { name: 'Performance overview.' })).toBeVisible()
    assert.equal(await app.evaluate(({ app }) => app.isPackaged), true)
    const info = await page.evaluate(() => window.journalAPI.appInfo())
    assert.equal(info.version, version)
    assert.equal(info.dataDirectory, directory)
    const initial = await page.evaluate(() => window.journalAPI.load())
    assert.equal(initial.trades.length, 0, 'New install starts empty')
    assert.deepEqual(initial.journals, {})
    await page.getByRole('navigation').getByRole('button', { name: 'Trade log', exact: true }).click()
    await page.locator('#field-contract').pressSequentially('mnq')
    await page.getByRole('navigation').getByRole('button', { name: 'Dashboard', exact: true }).click()
    await page.getByRole('button', { name: 'Keep editing', exact: true }).click()
    await page.locator('#field-notes').pressSequentially('Before recovery')
    await page.getByRole('button', { name: 'Restore typing', exact: true }).click()
    await page.locator('#field-notes').click()
    await page.locator('#field-notes').press('End')
    await page.locator('#field-notes').pressSequentially(' and after')
    await expect(page.locator('#field-notes')).toHaveValue('Before recovery and after')
    await expect(page.locator('#field-contract')).toHaveValue('MNQ')
    assert.ok(existsSync(path.join(directory, 'input-focus-diagnostics.jsonl')))
    await page.getByRole('navigation').getByRole('button', { name: 'Dashboard', exact: true }).click()
    await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
    const originalBounds = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].getBounds())
    await page.getByRole('button', { name: 'Pin window on top', exact: true }).click()
    await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isAlwaysOnTop())).toBe(true)
    assert.deepEqual(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].getBounds()), originalBounds)
    await page.getByRole('button', { name: 'Enable minimalist mode', exact: true }).click()
    await expect(page.locator('.quick-toolbar').getByRole('button', { name: 'Unpin window', exact: true })).toHaveAttribute('aria-pressed', 'true')
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isAlwaysOnTop()), true)
    await page.locator('.quick-toolbar').getByRole('button', { name: 'Exit minimalist mode', exact: true }).click()
    await page.getByRole('navigation').getByRole('button', { name: 'Dashboard', exact: true }).click()

    await page.getByRole('button', { name: 'Explore sample data' }).click()
    await page.getByLabel('From date', { exact: true }).fill('2020-01-01')
    await expect(page.locator('.save-status')).toHaveText('Saved locally')
    await page.getByRole('navigation').getByRole('button', { name: 'Settings', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Version and updates' })).toContainText(`v${version}`)
    await expect(page.getByRole('region', { name: 'Version and updates' })).toContainText('Updates are installed manually.')
    await page.getByRole('navigation').getByRole('button', { name: 'Import trades', exact: true }).click()
    await page.getByLabel('Trade CSV', { exact: true }).setInputFiles({ name: 'smoke.csv', mimeType: 'text/csv', buffer: Buffer.from('Symbol,PnL,PnL unit,Position size,Stop loss (points),Take profit (points),Notes\nMNQ,25,POINTS,3,10,30,Packaged import notes') })
    await page.getByRole('button', { name: 'Import 1 trades', exact: true }).click()
    await expect(page.locator('.import-page')).toContainText('Imported 1 trades: 0 completed, 1 unfinished.')
    await page.getByRole('navigation').getByRole('button', { name: 'Account manager', exact: true }).click()
    await page.getByRole('button', { name: 'Add account', exact: true }).click()
    await page.getByLabel('Account name', { exact: true }).fill('RELEASE CHECK')
    await page.getByLabel('Account purchase cost', { exact: true }).fill('150')
    await page.getByRole('button', { name: 'Save account', exact: true }).click()
    await expect(page.locator('.save-status')).toHaveText('Saved locally')
    await app.close(); app = await electron.launch({ executablePath, env, timeout: 30000 }); page = await app.firstWindow()
    await expect(page.locator('.stat-card').first()).toContainText('64 completed trades')
    const persisted = await page.evaluate(() => window.journalAPI.load())
    assert.equal(persisted.trades.length, 65)
    assert.equal(persisted.alwaysOnTop, true)
    await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isAlwaysOnTop())).toBe(true)
    await page.getByRole('button', { name: 'Unpin window', exact: true }).click()
    await expect.poll(() => app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isAlwaysOnTop())).toBe(false)
    assert.equal(persisted.accounts[0].name, 'RELEASE CHECK')
    assert.equal(persisted.accounts[0].events[0].cost, 150)
    assert.equal(persisted.lastFilters.dashboard.filters.from, '2020-01-01')
    await expect(page.getByLabel('From date', { exact: true })).toHaveValue('2020-01-01')
    assert.ok(persisted.trades.some(t => t.values.notes === 'Packaged import notes' && t.values.pnl === 25 && t.values.pnlUnit === 'POINTS' && t.values.tradeRR === 3 && t.values.realizedRR === 25 / 30))
    console.log(`PASS: packaged Windows ${version} starts offline, contains no journal data, displays its version, and retains SQLite trades across restarts.`)
    console.log('Isolated profile:', directory)
  } finally { await app?.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
