import { useMemo, useState } from 'react'
import { Plus, Pencil, Trash2, Download } from 'lucide-react'
import { isComplete, type JournalData } from '../lib/model'
import { accountError, accountKey, accountNames, accountReport, actionNames, eventError, localStamp, type AccountEvent, type PropAccount, type AccountAction } from '../lib/accounts'
import { money, number } from '../lib/format'
import { csvCell, downloadFile } from '../lib/storage'
import { Modal } from './ui'
import './AccountManager.css'

type Update = (change: (current: JournalData) => JournalData) => Promise<boolean>
const optionalNumber = (v: string) => v === '' ? undefined : Number(v)
function AccountEditor({ account, existing, names, onSave, onClose }: { account: PropAccount; existing: boolean; names: string[]; onSave: (a: PropAccount, cost: number) => Promise<boolean>; onClose: () => void }) {
  const [draft, setDraft] = useState(account), [cost, setCost] = useState('0'), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const change = (patch: Partial<PropAccount>) => setDraft(current => ({ ...current, ...patch }))
  return <Modal title={existing ? 'Edit account details' : 'Set up prop account'} onClose={() => { if (!busy) onClose() }}><form onSubmit={async e => {
    e.preventDefault(); const candidate = { ...draft, name: accountKey(draft.name), firm: draft.firm.trim() }
    const issue = accountError(candidate)
    if (issue || !Number.isFinite(Number(cost)) || Number(cost) < 0) { setError(issue || 'Enter a nonnegative purchase cost.'); return }
    setBusy(true); setError('')
    try { if (await onSave(candidate, Number(cost))) onClose(); else setError('Could not save. Retry without closing this window.') } catch (e) { setError((e as Error).message) } finally { setBusy(false) }
  }}><div className="form-grid two-col">
    <label>Account name<input aria-label="Account name" autoFocus required value={draft.name} disabled={existing} list="managed-account-names" onChange={e => change({ name: e.target.value.toUpperCase() })} /><datalist id="managed-account-names">{names.map(n => <option key={n}>{n}</option>)}</datalist><span className="help-text">Matches the trade logger, ignoring case.</span></label>
    <label>Prop firm<input aria-label="Prop firm" value={draft.firm} onChange={e => change({ firm: e.target.value })} /></label>
    <label>Balance starts at<input aria-label="Balance starts at" required type="datetime-local" value={draft.openedAt} onChange={e => change({ openedAt: e.target.value })} /></label>
    <label>Starting trading balance<input aria-label="Starting trading balance" required type="number" min="0" step="0.01" value={draft.startingBalance} onChange={e => change({ startingBalance: Number(e.target.value) })} /></label>
    <label>Initial account stage<select aria-label="Initial account stage" value={draft.initialStage} onChange={e => change({ initialStage: e.target.value as 'eval' | 'funded' })}><option value="eval">Evaluation</option><option value="funded">Funded</option></select></label>
    {!existing && <label>Account purchase cost<input aria-label="Account purchase cost" required type="number" min="0" step="0.01" value={cost} onChange={e => setCost(e.target.value)} /></label>}
    <label>Maximum drawdown amount<input aria-label="Maximum drawdown amount" type="number" min="0.01" step="0.01" value={draft.maxDrawdown ?? ''} onChange={e => change({ maxDrawdown: optionalNumber(e.target.value) })} placeholder="Optional" /></label>
    <label>Drawdown type<select aria-label="Drawdown type" value={draft.drawdownMode} onChange={e => change({ drawdownMode: e.target.value as PropAccount['drawdownMode'] })}><option value="static">Static</option><option value="eod">EOD trailing</option><option value="live">Live trailing</option></select></label>
    <label>Daily loss limit (DLL)<input aria-label="Daily loss limit (DLL)" type="number" min="0.01" step="0.01" value={draft.dailyLossLimit ?? ''} onChange={e => change({ dailyLossLimit: optionalNumber(e.target.value) })} placeholder="Optional" /></label>
    <label>Default payout share (%)<input aria-label="Default payout share (%)" required type="number" min="0" max="100" step="0.01" value={draft.payoutShare} onChange={e => change({ payoutShare: Number(e.target.value) })} /></label>
    <label className="full-width">Account notes<textarea rows={3} value={draft.notes} onChange={e => change({ notes: e.target.value })} /></label>
  </div><p className="help-text">The starting balance is the balance immediately before trades at this date/time. Earlier trades remain in the journal but are excluded from this account balance. Use actions for resets and funding changes to preserve their history.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button className="secondary" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>Save account</button></div></form></Modal>
}
function ActionEditor({ event, account, onSave, onClose }: { event: AccountEvent; account: PropAccount; onSave: (e: AccountEvent) => Promise<boolean>; onClose: () => void }) {
  const [draft, setDraft] = useState(event), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const change = (patch: Partial<AccountEvent>) => setDraft(current => ({ ...current, ...patch }))
  const payout = (withdrawal: number, share: number) => change({ withdrawal, share, received: Math.round(withdrawal * share) / 100 })
  return <Modal title="Record account action" onClose={() => { if (!busy) onClose() }}><form onSubmit={async e => {
    e.preventDefault(); const issue = eventError(draft)
    if (issue) { setError(issue); return }
    if (!['purchase', 'fee'].includes(draft.type) && draft.at < account.openedAt) { setError('Balance actions must be at or after the account starting date/time.'); return }
    setBusy(true); setError('')
    try { if (await onSave(draft)) onClose(); else setError('Could not save. Retry without closing this window.') } finally { setBusy(false) }
  }}><div className="form-grid two-col">
    <label>Action<select aria-label="Action" value={draft.type} onChange={e => { const type = e.target.value as AccountAction; setDraft({ id: draft.id, at: draft.at, type, cost: 0, notes: '', ...(type === 'reset' ? { balance: account.startingBalance, stage: 'eval' as const } : {}), ...(type === 'payout' ? { withdrawal: 0, share: account.payoutShare, received: 0 } : {}) }) }}>{Object.entries(actionNames).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>
    <label>Action date/time<input aria-label="Action date/time" required type="datetime-local" value={draft.at} onChange={e => change({ at: e.target.value })} /></label>
    <label>Cash cost / fee<input aria-label="Cash cost / fee" required type="number" min="0" step="0.01" value={draft.cost} onChange={e => change({ cost: Number(e.target.value) })} /><span className="help-text">Real money paid; does not reduce the trading balance.</span></label>
    {['reset', 'funded', 'adjustment'].includes(draft.type) && <label>New trading balance{draft.type === 'funded' && ' (optional)'}<input aria-label={draft.type === 'funded' ? 'New trading balance (optional)' : 'New trading balance'} required={draft.type !== 'funded'} type="number" step="0.01" value={draft.balance ?? ''} onChange={e => change({ balance: optionalNumber(e.target.value) })} /><span className="help-text">{draft.type === 'funded' ? 'Blank keeps the balance. Funding starts a new drawdown baseline.' : 'Replaces the balance; earlier activity remains in the ledger.'}</span></label>}
    {draft.type === 'reset' && <label>Stage after reset<select aria-label="Stage after reset" value={draft.stage} onChange={e => change({ stage: e.target.value as 'eval' | 'funded' })}><option value="eval">Evaluation</option><option value="funded">Funded</option></select></label>}
    {draft.type === 'peak' && <label>Observed peak equity<input aria-label="Observed peak equity" required type="number" step="0.01" value={draft.peak ?? ''} onChange={e => change({ peak: optionalNumber(e.target.value) })} /><span className="help-text">Raises a live trailing reference; does not add profit or cash.</span></label>}
    {draft.type === 'payout' && <><label>Trading balance deduction<input aria-label="Trading balance deduction" required type="number" min="0.01" step="0.01" value={draft.withdrawal ?? ''} onChange={e => payout(Number(e.target.value), draft.share ?? account.payoutShare)} /></label><label>Your payout share (%)<input aria-label="Your payout share (%)" required type="number" min="0" max="100" step="0.01" value={draft.share ?? account.payoutShare} onChange={e => payout(draft.withdrawal || 0, Number(e.target.value))} /></label><label>Actual cash received<input aria-label="Actual cash received" required type="number" min="0" step="0.01" value={draft.received ?? ''} onChange={e => change({ received: Number(e.target.value) })} /><span className="help-text">Calculated from the split; override to match the actual deposit. Avoid counting the same withheld fee again as a cash cost.</span></label></>}
    <label className="full-width">Action notes<textarea rows={3} value={draft.notes} onChange={e => change({ notes: e.target.value })} placeholder="Receipt, payout reference, reset reason..." /></label>
  </div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>Save action</button></div></form></Modal>
}
export default function AccountManager({ data, update }: { data: JournalData; update: Update }) {
  const names = accountNames(data)
  const [selected, setSelected] = useState(names[0] || ''), [asOf, setAsOf] = useState(localStamp().slice(0, 10)), [editor, setEditor] = useState<PropAccount>(), [action, setAction] = useState<AccountEvent>(), [deleting, setDeleting] = useState<AccountEvent>(), [page, setPage] = useState(0), [busy, setBusy] = useState(false)
  const account = data.accounts?.find(a => accountKey(a.name) === selected)
  const complete = useMemo(() => new Set(data.trades.filter(t => isComplete(t, data.fields)).map(t => t.id)), [data.trades, data.fields])
  const reports = useMemo(() => (data.accounts || []).map(a => ({ account: a, report: accountReport(a, data, asOf, complete) })), [data, asOf, complete])
  const report = reports.find(r => r.account.id === account?.id)?.report
  const totals = reports.reduce((sum, r) => ({ costs: sum.costs + r.report.costs, cash: sum.cash + r.report.cash, net: sum.net + r.report.netCash }), { costs: 0, cash: 0, net: 0 })
  const fmt = (n: number | undefined) => n === undefined ? 'Not set' : money(n, data.currency)
  const setup = (name: string) => {
    const dates = data.trades.filter(t => accountKey(t.values.account) === accountKey(name)).map(t => String(t.values.date || '')).filter(d => /^\d{4}-\d{2}-\d{2}$/.test(d)).sort()
    setEditor({ id: crypto.randomUUID(), name, firm: '', openedAt: `${dates[0] || asOf}T00:00`, startingBalance: 50000, initialStage: 'eval', drawdownMode: 'static', payoutShare: 90, notes: '', events: [] })
  }
  const saveAccount = async (a: PropAccount, cost: number) => {
    if ((data.accounts || []).some(old => old.id !== a.id && accountKey(old.name) === accountKey(a.name))) throw new Error('That account name is already managed. Select it to edit its details.')
    const existing = data.accounts?.some(old => old.id === a.id)
    const candidate = existing ? { ...a, events: data.accounts!.find(old => old.id === a.id)!.events } : { ...a, events: [{ id: `purchase-${a.id}`, type: 'purchase' as const, at: a.openedAt, cost, notes: 'Initial account purchase' }] }
    const saved = await update(current => ({ ...current, accounts: current.accounts?.some(old => old.id === a.id) ? current.accounts.map(old => old.id === a.id ? candidate : old) : [...(current.accounts || []), candidate] }))
    if (saved) { setSelected(accountKey(a.name)); setPage(0) }
    return saved
  }
  const saveAction = (event: AccountEvent) => update(current => ({ ...current, accounts: current.accounts?.map(a => a.id !== account!.id ? a : { ...a, events: a.events.some(e => e.id === event.id) ? a.events.map(e => e.id === event.id ? event : e) : [...a.events, event] }) }))
  const exportLedger = () => {
    if (!report || !account) return
    const rows = [['Account', 'Date/time', 'Action', 'Trading PnL', 'Cash cost', 'Balance deduction', 'Cash received', 'Trading balance', 'Stage', 'Notes'], ...[...report.rows].reverse().map(r => [account.name, r.at, r.label, r.pnl ?? '', r.cost, r.withdrawal, r.cash, r.balance, r.stage, r.notes])]
    downloadFile(`account-ledger-${asOf}.csv`, '\uFEFF' + rows.map(r => r.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8')
  }
  const pages = Math.max(1, Math.ceil((report?.rows.length || 0) / 50)), currentPage = Math.min(page, pages - 1)
  return <>
    <div className="page-heading"><div><div className="eyebrow">YOUR PROP ACCOUNT BOOKS</div><h1>Account manager<span className="heading-dot">.</span></h1><p>Track trading capital, real costs, and money paid out to you.</p></div><button className="primary" onClick={() => setup('')}><Plus size={16} />Add account</button></div>
    <div className="account-controls"><label>Account<select aria-label="Managed account" value={selected} onChange={e => { setSelected(e.target.value); setPage(0) }}><option value="">Choose an account</option>{names.map(name => <option key={name} value={name}>{name}{data.accounts?.some(a => accountKey(a.name) === name) ? '' : ' — needs details'}</option>)}</select></label><label>As of date<input aria-label="As of date" type="date" required value={asOf} onChange={e => { if (e.target.value) { setAsOf(e.target.value); setPage(0) } }} /></label></div>
    <div className="account-summary"><section className="panel padded"><span>All managed accounts · cash costs</span><strong>{fmt(totals.costs)}</strong></section><section className="panel padded"><span>Actual payouts received</span><strong>{fmt(totals.cash)}</strong></section><section className="panel padded"><span>Net real cash · payouts minus costs</span><strong className={totals.net < 0 ? 'negative' : 'positive'}>{fmt(totals.net)}</strong></section></div>
    {!account ? <section className="panel padded"><h2>{selected || 'Choose or add an account'}</h2><p>Existing names from the trade log are available above. Set their opening balance and account details to calculate balances. New managed names become trade-entry dropdown options.</p>{selected && <button className="primary" onClick={() => setup(selected)}>Set up account details</button>}</section> : report && <>
      <section className="panel padded"><div className="section-line"><div><h2>{account.name} <span className="tag">{report.stage.toUpperCase()}</span></h2><p className="help-text">{account.firm || 'Prop firm not specified'} · {account.drawdownMode === 'static' ? 'Static' : account.drawdownMode === 'eod' ? 'EOD trailing' : 'Live trailing'} drawdown</p></div><div className="button-row"><button className="secondary" onClick={() => setEditor(account)}><Pencil size={14} />Edit account</button><button className="primary" onClick={() => setAction({ id: crypto.randomUUID(), at: `${asOf}T${localStamp().slice(11)}`, type: 'fee', cost: 0, notes: '' })}><Plus size={14} />Record action</button></div></div>
        <div className="account-detail-grid">{[['Trading balance', report.notStarted ? 'Not opened yet' : fmt(report.balance)], ['Trading PnL since opening', fmt(report.pnl)], ['Total costs', fmt(report.costs)], ['Actual payouts received', fmt(report.cash)], ['Payouts deducted from balance', fmt(report.withdrawals)], ['Net real cash', fmt(report.netCash)], ['Estimated drawdown floor', fmt(report.threshold)], ['Remaining to drawdown floor', fmt(report.drawdownRoom)], ['Daily loss limit', fmt(account.dailyLossLimit)], ['Selected-day trading PnL', fmt(report.dayPnl)], ['Remaining DLL (closed trades)', fmt(report.dllRoom)], ['Default payout split', `${number(account.payoutShare)}%`]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
        {(report.skipped > 0 || report.beforeOpening > 0 || report.unfinished > 0) && <p className="notice">Balance coverage: {report.skipped} trade(s) lack a usable exit date or dollar PnL/multiplier; {report.beforeOpening} precede the starting balance; {report.unfinished} are unfinished. These trades are excluded from the balance estimate.</p>}
        {account.notes && <p className="account-notes">{account.notes}</p>}
      </section>
      <section className="panel account-ledger"><div className="panel-heading"><div><h2>Account ledger</h2><p>Actions and closed trades in date/time order. Cash costs are separate from trading PnL.</p></div><button className="secondary compact" onClick={exportLedger}><Download size={14} />Export ledger</button></div><div className="table-scroll"><table><thead><tr><th>Date / action</th><th>Trading PnL</th><th>Cash cost</th><th>Balance deduction</th><th>Cash received</th><th>Balance after</th><th>Actions</th></tr></thead><tbody>{report.rows.slice(currentPage * 50, (currentPage + 1) * 50).map(r => <tr key={`${r.event ? 'action' : 'trade'}-${r.id}`}><td><strong>{r.label}</strong><small>{r.at.replace('T', ' ')} · {r.stage}</small>{r.notes && <details><summary>Notes</summary><p>{r.notes}</p></details>}</td><td>{r.pnl === undefined ? '—' : fmt(r.pnl)}</td><td>{fmt(r.cost)}</td><td>{fmt(r.withdrawal)}</td><td>{fmt(r.cash)}</td><td>{fmt(r.balance)}</td><td>{r.event && <div className="button-row"><button className="icon-button" aria-label={`Edit ${r.label} ${r.at}`} onClick={() => setAction(r.event)}><Pencil size={14} /></button><button className="icon-button danger" aria-label={`Delete ${r.label} ${r.at}`} onClick={() => setDeleting(r.event)}><Trash2 size={14} /></button></div>}</td></tr>)}</tbody></table></div><div className="pagination"><span>{report.rows.length} records</span><div className="button-row"><button className="secondary compact" disabled={!currentPage} onClick={() => setPage(currentPage - 1)}>Previous</button><span>{currentPage + 1} / {pages}</span><button className="secondary compact" disabled={currentPage + 1 >= pages} onClick={() => setPage(currentPage + 1)}>Next</button></div></div></section>
    </>}
    <section className="account-methodology"><h3>How account balances work</h3><p>All amounts use {data.currency}; no foreign-exchange conversion is performed. Closed-trade PnL changes trading balances. Purchases, activation fees, reset costs, and subscriptions change real cash costs. A payout reduces the trading balance by the full deduction but credits only the actual cash you receive. Resets and funding changes establish a new drawdown baseline without erasing earlier records. Profit factor remains gross trading profit / gross trading loss.</p><p>Drawdown and DLL are estimates from logged activity, not live prop-firm monitoring. Static uses the cycle's starting balance. EOD trailing uses previous calendar-day closing balances, in the journal's local date convention; today's EOD threshold is provisional. Live trailing uses logged closed-trade highs plus any “Observed equity high” actions you enter. Intraday lows, firm-specific session cutoffs, capped trailing floors, and open-position losses are not inferred. Compare the estimate with your firm's reported limit. DLL uses net closed-trade losses for the selected calendar date, excluding payouts and fees.</p></section>
    {editor && <AccountEditor key={editor.id} account={editor} existing={!!data.accounts?.some(a => a.id === editor.id)} names={names} onSave={saveAccount} onClose={() => setEditor(undefined)} />}
    {action && account && <ActionEditor key={action.id} event={action} account={account} onSave={saveAction} onClose={() => setAction(undefined)} />}
    {deleting && account && <Modal title="Delete account action?" onClose={() => setDeleting(undefined)}><p>Remove {actionNames[deleting.type]} from {account.name}? The ledger and balances will recalculate. Trade records remain intact.</p><div className="modal-actions"><button className="secondary" onClick={() => setDeleting(undefined)}>Cancel</button><button className="danger-button" disabled={busy} onClick={async () => { setBusy(true); try { if (await update(current => ({ ...current, accounts: current.accounts?.map(a => a.id === account.id ? { ...a, events: a.events.filter(e => e.id !== deleting.id) } : a) }))) setDeleting(undefined) } finally { setBusy(false) } }}>Delete action</button></div></Modal>}
  </>
}
