import { useRef, useState } from 'react'
import { Archive, Download, Moon, Pencil, Plus, RotateCcw, Sun, Upload } from 'lucide-react'
import { activeFields, isComplete, isNumeric, parseBackup, today, validateField, type Field, type FieldType, type JournalData } from '../lib/model'
import { downloadFile, storageMode } from '../lib/storage'
import { Modal } from './ui'
import ReleaseInfo from './ReleaseInfo'
function FieldEditor({ field, fields, trades, onSave, onClose }: { field: Field; fields: Field[]; trades: JournalData['trades']; onSave: (field: Field) => Promise<boolean>; onClose: () => void }) {
  const [draft, setDraft] = useState<Field>({ ...field }), [options, setOptions] = useState(field.options.join(', ')), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const update = (patch: Partial<Field>) => setDraft(prev => ({ ...prev, ...patch }))
  const candidate = { ...draft, name: draft.name.trim(), options: [...new Set(options.split(/[,\n]/).map(o => o.trim()).filter(Boolean))] }
  const nextFields = fields.some(f => f.id === field.id) ? fields.map(f => f.id === field.id ? candidate : f) : [...fields, candidate]
  const before = trades.filter(t => isComplete(t, fields)).length, after = trades.filter(t => isComplete(t, nextFields)).length
  return <Modal title={fields.some(f => f.id === field.id) ? 'Edit characteristic' : 'Add a characteristic'} onClose={onClose}><form onSubmit={async e => { e.preventDefault(); const message = validateField(candidate, fields); if (message) { setError(message); return } setBusy(true); if (await onSave(candidate)) onClose(); setBusy(false) }}>
    <div className="form-grid two-col"><label className="full-width">Name<input autoFocus value={draft.name} onChange={e => update({ name: e.target.value })} placeholder="e.g. Mood, Market condition, Risk %" /></label><label>Value type<select value={draft.type} disabled={draft.builtin} onChange={e => update({ type: e.target.value as FieldType, min: e.target.value === 'score' ? 1 : undefined, max: e.target.value === 'score' ? 5 : undefined })}>{['text', 'decimal', 'integer', 'percent', 'score', 'date', 'time'].map(type => <option value={type} key={type}>{({ text: 'Text / dropdown', decimal: 'Decimal', integer: 'Integer', percent: 'Percent', score: 'Score', date: 'Date', time: 'Time' } as Record<string, string>)[type]}</option>)}</select></label>
      {isNumeric(draft) && <><label>Minimum {draft.type !== 'score' && '(optional)'}<input type="number" step={['integer', 'score'].includes(draft.type) ? '1' : 'any'} value={draft.min ?? ''} onChange={e => update({ min: e.target.value === '' ? undefined : Number(e.target.value) })} /></label><label>Maximum {draft.type !== 'score' && '(optional)'}<input type="number" step={['integer', 'score'].includes(draft.type) ? '1' : 'any'} value={draft.max ?? ''} onChange={e => update({ max: e.target.value === '' ? undefined : Number(e.target.value) })} /></label></>}
      {draft.type === 'text' && draft.id !== 'direction' && <label className="full-width">Dropdown options<textarea value={options} onChange={e => setOptions(e.target.value)} rows={3} placeholder="Happy, Calm, Tired, Frustrated" /><span className="help-text">Separate options with commas or new lines. New values entered on a trade are remembered.</span></label>}
    </div><div className="field-flags"><label className="check-label"><input type="checkbox" checked={draft.required} onChange={e => update({ required: e.target.checked })} />Required to complete a trade</label><label className="check-label"><input type="checkbox" checked={draft.filter} onChange={e => update({ filter: e.target.checked })} />Available as a dashboard and master log filter</label><label className="check-label"><input type="checkbox" checked={draft.analyze} onChange={e => update({ analyze: e.target.checked })} />Generate an automatic analytics breakdown</label></div>
    {before !== after && <div className="notice">Applying this changes your completed trade count from {before} to {after}. Incomplete trades move to the trade log.</div>}
    {error && <p role="alert" className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save characteristic'}</button></div>
  </form></Modal>
}
export default function Preferences({ data, update, onDemo, notify }: { data: JournalData; update: (change: (current: JournalData) => JournalData) => Promise<boolean>; onDemo: () => void; notify: (message: string) => void }) {
  const [editing, setEditing] = useState<Field | null>(null), [search, setSearch] = useState(''), [restore, setRestore] = useState<JournalData | null>(null), [removeDemo, setRemoveDemo] = useState(false)
  const [importError, setImportError] = useState(''), [busy, setBusy] = useState(false)
  const input = useRef<HTMLInputElement>(null)
  const fields = activeFields(data.fields), archived = data.fields.filter(f => f.archived)
  const backup = () => { downloadFile(`turbo-journal-${today()}.json`, JSON.stringify(data, null, 2), 'application/json'); notify('Backup exported with trades, settings, and daily journal pages.') }
  const saveField = async (field: Field) => {
    const saved = await update(current => ({ ...current, fields: current.fields.some(f => f.id === field.id) ? current.fields.map(f => f.id === field.id ? field : f) : [...current.fields, field] }))
    if (saved) notify('Characteristic saved. Trade completion and analytics are up to date.')
    return saved
  }
  return <>
    <div className="page-heading"><div><div className="eyebrow">BUILT AROUND YOUR PROCESS</div><h1>Make it yours<span className="heading-dot">.</span></h1><p>Your journal should fit the way you trade.</p></div><button className="primary" onClick={() => setEditing({ id: crypto.randomUUID(), name: '', type: 'text', required: false, filter: true, analyze: true, options: [] })}><Plus size={17} />Add characteristic</button></div>
    <div className="settings-top-grid"><section className="panel appearance-panel"><div className="panel-heading"><div><h2>Pick your atmosphere</h2><p>Teal and racing orange. An ’80s pit-lane palette.</p></div></div><div className="theme-choices"><button className={`theme-choice theme-night ${data.theme === 'dark' ? 'chosen' : ''}`} onClick={() => { void update(current => ({ ...current, theme: 'dark' })) }} aria-pressed={data.theme === 'dark'}><Moon size={20} /><strong>Midnight drive</strong><span>Dark mode</span><div className="swatches"><i /><i /><i /><i /><i /></div></button><button className={`theme-choice theme-day ${data.theme === 'light' ? 'chosen' : ''}`} onClick={() => { void update(current => ({ ...current, theme: 'light' })) }} aria-pressed={data.theme === 'light'}><Sun size={20} /><strong>Race day</strong><span>Light mode</span><div className="swatches"><i /><i /><i /><i /><i /></div></button></div></section>
      <section className="panel display-panel"><div className="panel-heading"><div><h2>The essentials</h2><p>Keep your results consistent.</p></div></div><label>Display currency<select value={data.currency} onChange={e => { const currency = e.target.value; void update(current => ({ ...current, currency })) }}>{['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY'].map(c => <option key={c}>{c}</option>)}</select></label><p className="help-text">Applies a currency label, without converting values. Keep trade PnL in one currency.</p><div className="storage-detail"><span className="status-dot" /><div><strong>{storageMode()}</strong><p>{window.journalAPI ? 'Saved in your desktop app’s SQLite database.' : 'Saved on this device in this browser. Desktop data is separate; transfer it with a backup.'}</p></div></div></section></div>
    <section className="panel"><div className="panel-heading"><div><h2>Trade characteristics <span className="tag">{fields.length}</span></h2><p>Required fields control completion. Enable filters and analytics for the details you want to explore.</p></div><input className="settings-search" aria-label="Find characteristic" placeholder="Find a characteristic…" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="notice inline-notice">Changes apply to existing trades too. Missing or invalid required values return a completed trade to the unfinished queue.</div>
    <div className="table-scroll"><table className="settings-table"><thead><tr><th>Characteristic</th><th>Value type</th><th>Range / options</th><th>Required</th><th>Filter</th><th>Analyze</th><th>Actions</th></tr></thead><tbody>{fields.filter(f => f.name.toLowerCase().includes(search.toLowerCase())).map(f => <tr key={f.id}><td><strong>{f.name}</strong>{!f.builtin && <span className="custom-label">CUSTOM</span>}</td><td><span className="tag">{f.type}</span></td><td className="options-cell">{isNumeric(f) ? `${f.min ?? 'No minimum'} → ${f.max ?? 'No maximum'}` : f.options.length ? <span title={f.options.join(', ')}>{f.options.slice(0, 4).join(', ')}{f.options.length > 4 ? ` +${f.options.length - 4}` : ''}</span> : '—'}</td>{(['required', 'filter', 'analyze'] as const).map(flag => <td key={flag}><input className="switch" type="checkbox" aria-label={`${f.name} ${flag}`} checked={f[flag]} onChange={e => { const checked = e.target.checked; void update(current => ({ ...current, fields: current.fields.map(item => item.id === f.id ? { ...item, [flag]: checked } : item) })) }} /></td>)}<td><div className="button-row"><button className="icon-button" aria-label={`Edit ${f.name}`} onClick={() => setEditing(f)}><Pencil size={15} /></button>{!f.builtin && <button className="icon-button" aria-label={`Archive ${f.name}`} onClick={() => { void saveField({ ...f, archived: true }) }}><Archive size={15} /></button>}</div></td></tr>)}</tbody></table></div></section>
    {!!archived.length && <details className="panel archived-panel"><summary>Archived characteristics ({archived.length})</summary><p className="help-text">Values are preserved. Restore a characteristic to include it again.</p>{archived.map(f => <div className="section-line" key={f.id}><span>{f.name}</span><button className="text-button" onClick={() => { void saveField({ ...f, archived: false }) }}><RotateCcw size={14} />Restore</button></div>)}</details>}
    <div className="settings-bottom-grid"><section className="panel padded"><h2>Your data, in your hands</h2><p className="muted">Back up your trades, characteristics, journal pages, and appearance. Restore a backup to move between browsers or the desktop app.</p><div className="button-row"><button className="secondary" onClick={backup}><Download size={16} />Export backup</button><button className="secondary" onClick={() => input.current?.click()}><Upload size={16} />Restore backup</button></div><input ref={input} type="file" accept=".json,application/json" className="sr-only" aria-label="Import backup file" onChange={async e => { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; try { const parsed = parseBackup(JSON.parse(await file.text())); setRestore(parsed); setImportError('') } catch (error) { setImportError(error instanceof Error ? error.message : 'Unable to read this file.') } }} />{importError && <p role="alert" className="form-error">{importError}</p>}</section><section className="panel padded"><h2>Take it for a spin</h2><p className="muted">Explore 64 clearly marked sample trades and a Mood characteristic. Your own entries are preserved.</p>{data.trades.some(t => t.demo) ? <button className="secondary" onClick={() => setRemoveDemo(true)}>Remove sample trades</button> : <button className="secondary" onClick={onDemo}>Add sample trades</button>}</section></div>
    <ReleaseInfo />
    {editing && <FieldEditor field={editing} fields={data.fields} trades={data.trades} onSave={saveField} onClose={() => setEditing(null)} />}
    {restore && <Modal title="Restore this backup?" onClose={() => setRestore(null)}><p>This replaces {data.trades.length} current trades and {Object.values(data.journals).filter(e => e.text).length} journal pages with <strong>{restore.trades.length} trades, {Object.values(restore.journals).filter(e => e.text).length} journal pages, and {restore.fields.length} characteristics</strong> from this backup.</p><p>A backup of your current data will download before the replacement.</p><div className="modal-actions"><button className="secondary" onClick={() => setRestore(null)}>Cancel</button><button className="primary" disabled={busy} onClick={async () => { setBusy(true); backup(); if (await update(() => restore)) { setRestore(null); notify('Backup restored.') } setBusy(false) }}>Back up current data & restore</button></div></Modal>}
    {removeDemo && <Modal title="Remove sample trades?" onClose={() => setRemoveDemo(false)}><p>This removes {data.trades.filter(t => t.demo).length} sample trades. Your own trades, journal pages, and characteristics are preserved.</p><div className="modal-actions"><button className="secondary" onClick={() => setRemoveDemo(false)}>Keep samples</button><button className="danger-button" onClick={async () => { if (await update(current => ({ ...current, trades: current.trades.filter(t => !t.demo) }))) { setRemoveDemo(false); notify('Sample trades removed.') } }}>Remove samples</button></div></Modal>}
  </>
}
